##### The script is used to visualize the PCA results generated by plink ######
### The PCA analysis was done on filtered SNPs detected by GATK using the script PCA_FilteredSNPs.sh

# Load the required packages
library(tidyverse)
library(ggplot2)
library(ggrepel)

# Set the variables
inputprefix <- "AllSamples_SNP.SG.Filtered"

######################
# Load data
pca <- read_table(paste0(inputprefix,".eigenvec"), col_names = F)
eigenval <- scan(paste0(inputprefix, ".eigenval"))

# Clean the data
# Remove the extra identical column with sample ID
pca <- pca[,-1]

# Set the column names
colnames(pca)[1] <- "SampleID"
colnames(pca)[2:ncol(pca)] <- paste0("PC",1:(ncol(pca)-1))


# Percentage variance explained
pve <- data.frame(PC = 1:(ncol(pca)-1), pve = eigenval/sum(eigenval)*100)

# Check PVE
# fig <- ggplot(pve, aes(PC, pve)) +
#         geom_bar(stat = "identity") +
#         ylab("Percentage Variance Explained")
# fig + theme_light()



# Add species information as we also want to see whether variants cluster by species
sp <- rep(NA, length(pca$SampleID))
sp[grep("CH", pca$SampleID)] <- "A.chrysopterus"
sp[grep("LU", pca$SampleID)] <- "A.leucokranos"
sp[grep("SA", pca$SampleID)] <- "A.sandaracinos"
sp[grep("GB", pca$SampleID)] <- "A.clarkii"
pca <- as_tibble(data.frame(pca, sp))


# Plot PCA
fig <- pca[which(pca$sp=="A.leucokranos"),] %>% 
  ggplot(aes(x = PC1, y = PC2, colour = sp, label = SampleID)) +
  geom_point(size = 2) + 
  guides(colour = guide_legend(title = "Species")) +
  ggtitle("PCA of Filtered SNPs") +
  labs(caption = paste("Dataset:",inputprefix)) + 
  xlab(paste0("PC1 (",round(pve[1,2], digits = 2),"%)")) +
  ylab(paste0("PC2 (",round(pve[2,2], digits = 2),"%)")) 
fig + theme_light() + 
  theme(plot.caption.position = "plot", plot.caption = element_text(size = 11)) +
  geom_label_repel(aes(label = SampleID),
                    size = 3,
                    box.padding   = 0.35,
                    point.padding = 0.5,
                    segment.color = "grey50",
                    max.overlaps = 35,
                    show.legend = F)

############# Finish ############# 


