##### This script is used to plot the population genomic statistics (Figure 4) #####
### The statistics was generated by the scripts of Simon Martin ###

# Load libraries
library(tidyverse)
library(ggrepel)
library(ggplot2)
library(ggtext)
library(RColorBrewer)
library(ggbiplot)
library(factoextra)
library(patchwork)
library(viridis)
library(readr)
library(dplyr)
library(wesanderson)

# Set the working directory
setwd("/Path/to/the/directory/with/input/files")


############# Figure 4 ################
### Load data
# Read in the file with pi, Fst, and dxy of all pairs of species, which was generated by popgenWindows.py
data_fst_dxy_pi <- read.csv("AllSpecies_popgenWindows.w50m100.csv", header = T, na.strings = "NaN")

# Read in the file with Fd of populations we're interested in, which was generated by ABBABABAwindows.py
# The groups we used:
#   P1 = SAN_AUS, P2 = SAN_PNG, P3 = CHR_PNG, outgroup = CLA
allchr.png.abba <- read.csv("ABBABABA.SAN_AUS.SAN_PNG.CHR_PNG.CLA.w50m100.csv", header = T,
               na.strings = "NaN")

### Plotting
## Figure 4A
# Plot Fst differences between F1-hybrids and both parental species from Papua New Guinea
# Define a function to calculate and plot difference in pairwise Fst
fun_diff_pairwise <- function(dataset, pop_pair_1, pop_pair_2, win_size, statistics) {
  
  # Preparing dataset
  diff_df <- dataset %>%
    drop_na() %>%
    select(c(scaffold, start, pop_pair_1, pop_pair_2)) %>% 
    mutate(diff = get(pop_pair_1)-get(pop_pair_2)) %>% # Calculate difference 
    mutate(q_99 = quantile(diff, probs = 0.99, na.rm = T)) %>% # Calculate quantile 99%
    mutate(q_01 = quantile(diff, probs = 0.01, na.rm = T)) %>% # Calculate quantile 1%
    mutate(outlier_q99  = case_when(diff >= q_99 ~ "above",
                                    diff < q_99 & diff > q_01 ~ "notoutlier",
                                    diff <= q_01 ~ "below")) %>% # whether the window is an outlier 
    # Median fst difference per chromosome
    group_by(scaffold) %>%
    dplyr::mutate(median_diff = median(diff, na.rm = T))
  
  # Plotting values across chromosomes
  ggplot(diff_df, aes(start, diff)) + 
    geom_rect(data = filter(diff_df, scaffold %% 2 == 1),
              fill = "grey92", color = "grey92", 
              xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf) + #color only odd chromosomes panel
    geom_point(aes(color = factor(outlier_q99, levels = c("notoutlier","below","above")))) +
    scale_color_manual(values = c("grey",wes_palette("FantasticFox1")[c(3,5)])) +
    geom_hline(data = diff_df, aes(yintercept = median_diff), size = 0.5, color = "black", linetype= "dotted") +
    facet_grid(~scaffold, scales = 'free_x', space = 'free_x', switch = 'x', labeller = labeller(scaffold = c(1:24))) +
    labs(x        = "chromosome",
         y        = statistics,
         title    = paste(pop_pair_1, "-", pop_pair_2, sep = " "),
         subtitle = paste(win_size, "windows", sep = " ")) +
    theme_light() +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          panel.grid = element_blank(),
          axis.title.x = element_blank(),
          axis.title.y = ggtext::element_markdown(color = "grey50"),
          panel.spacing.x = unit(1, "mm"),
          strip.background = element_blank(),
          strip.text.x = element_text(color = "black"),
          panel.border = element_blank(),
          legend.position = "none",
          legend.title = element_blank())
}

# Formula: F1-parent divergence = Fst of CHR-F1  - Fst of SAN-F1 
fst <- fun_diff_pairwise(data_fst_dxy_pi, "Fst_CHR_PNG_leuco_F1", "Fst_leuco_F1_SAN_PNG", "50kb", "*F<sub>ST<sub>* difference")
ggsave(filename = "FstDifference_CHP-F1_SAN-F1.png", plot = fst, dpi = "print")


## Figure 4B
# Plot the distribution of fdM across all background windows and highly divergent windows biased toward A. sandaracinos
# Background windows are labeled 'notoutlier' and highly divergent windows biased toward A. sandaracinos are labeled 'below' in fst$data$outlier_q99

fdm_df <- left_join(allchr.png.abba, fst$data, by = c("scaffold", "start")) %>%
  drop_na() %>%
  select(c(scaffold, start, fdM, outlier_q99)) %>%
  mutate(WindowType = case_when(outlier_q99 == 'below' ~ 'divergent_san',
                                outlier_q99 == 'notoutlier' ~ 'background',
                                outlier_q99 == 'above' ~ 'divergent_chp'))

order_x <- c("background","divergent_san","divergent_chp")

fdm <- ggplot(fdm_df, aes(x = factor(WindowType, levels = order_x), y = fdM, colour = factor(WindowType, levels = order_x))) +
  geom_boxplot(outlier.shape = NA, width = 0.6) +
  scale_color_manual(values = c("grey30", wes_palette("FantasticFox1")[c(3,5)])) +
  geom_jitter(alpha = 0.4, width = 0.15, size = 0.5) +
  labs(title = "Distribution of fdM",
       y = "*F<sub>dM</sub>*") +
  scale_x_discrete(labels = c("Background\nwindows",
                              "Highly divergent\nwindows (A.sandaracinos)",
                              "Highly divergent\nwindows (A.chrysopterus)")) +
  theme_light() +
  theme(axis.title.x = element_blank(),
        axis.title.y = ggtext::element_markdown(colour = "grey50"),
        axis.text.x = element_text(colour = "grey50"),
        legend.position = "none",
        legend.title = element_blank())

ggsave(filename = "Distribution_fdM.png", plot = fdm, dpi = "print")


################ Finish ################

