##### This script is used to extract outliers windows coordinate to be used for the GO analysis #####
### The statistics was generated by the scripts of Simon Martin ###
### Author: Sarah Schmid

# Load libraries
library(ggrepel)
library(tidyverse)
library(patchwork)
library(here)


############# Figure 4 ################
### Load data
# Read in the file with pi, Fst, and dxy of all pairs of species, which was generated by popgenWindows.py
data_fst_dxy_pi <- read_delim("../results/all_species_popgen.w50m100.csv.gz", na = "Nan") %>%
  mutate(scaffold = as.numeric(str_remove(scaffold, "^Chr")))


# Plotting ####

## Figure 4A ###################################################################
# Plot Fst differences between F1-hybrids and both parental species from Papua New Guinea
# Define a function to calculate and plot difference in pairwise Fst
fun_diff_pairwise <- function(dataset, pop_pair_1, pop_pair_2, win_size, statistics) {
  
  # Preparing dataset
  diff_df <- dataset %>%
    drop_na() %>%
    dplyr::select(scaffold, start, end, pop_pair_1, pop_pair_2) %>% 
    mutate(diff = get(pop_pair_1)-get(pop_pair_2)) %>% # Calculate difference 
    mutate(q_99 = quantile(diff, probs = 0.99, na.rm = T)) %>% # Calculate quantile 99%
    mutate(q_01 = quantile(diff, probs = 0.01, na.rm = T)) %>% # Calculate quantile 1%
    mutate(outlier_q99  = case_when(diff >= q_99 ~ "above",
                                    diff < q_99 & diff > q_01 ~ "notoutlier",
                                    diff <= q_01 ~ "below")) %>% # whether the window is an outlier 
    # Median fst difference per chromosome
    group_by(scaffold) %>%
    dplyr::mutate(median_diff = median(diff, na.rm = T)) %>%
    
    # Keep only windows which are outlier for both "below" and "above" and keep only columns of interest for GO analysis
    dplyr::filter(outlier_q99 %in% c("above", "below")) %>%
    dplyr::select(scaffold, start, end)
    
  # Write table with results
  write_delim(x = diff_df, file = "../results/fst_diff_parents_f1_q01_q99_outlier_windows.txt", delim = "\t")
}

# Formula: F1-parent divergence = Fst of CHR-F1  - Fst of SAN-F1 
fst <- fun_diff_pairwise(data_fst_dxy_pi, "Fst_CHR_PNG_leuco_F1", "Fst_leuco_F1_SAN_PNG", "50kb", "*F<sub>ST<sub>* difference")
 
