############# Figure 4 ################
##### This script is used to plot the population genomic statistics (Figure 4) #####
### The statistics was generated by the scripts of Simon Martin ###
###
### Authors: Sarah Schmid, Wan-Ting Huang
###
########################################

# Load libraries ---------------------------------------------------------------
library(ggrepel)
library(tidyverse)
library(patchwork)
library(here)


# Load data ------------------------------------------------------------------
# Read in the file with pi, Fst, and dxy of all pairs of species, which was generated by popgenWindows.py
data_fst_dxy_pi <- read.csv("../results/all_species_popgen.w50m100.csv.gz", header = T, na.strings = "NaN") %>%
  mutate(scaffold = as.numeric(str_remove(scaffold, "^Chr")))

# Read in the file with Fd of populations we're interested in, which was generated by ABBABABAwindows.py
# The groups we used:
#   P1 = SAN_AUS, P2 = SAN_PNG, P3 = CHR_PNG, outgroup = CLA
allchr.san.abba <- read.csv("../results/fd.san_aus.san_png.chr_png.cla.w50m100.csv.gz", header = T, na.strings = "NaN") %>%
  mutate(scaffold = as.numeric(str_remove(scaffold, "^Chr")))

# The groups we used:
#   P1 = CHR_FIJI, P2 = CHR_PNG, P3 = SAN_PNG, outgroup = CLA
allchr.chr.abba <- read.csv("../results/fd.chr_fiji.chr_png.san_png.cla.w50m100.csv.gz", header = T, na.strings = "NaN") %>%
  mutate(scaffold = as.numeric(str_remove(scaffold, "^Chr")))


# Plotting ---------------------------------------------------------------------

## Figure 4A -------------------------------------------------------------------
# Plot Fst differences between F1-hybrids and both parental species from Papua New Guinea
# Define a function to calculate and plot difference in pairwise Fst
fun_diff_pairwise <- function(dataset, pop_pair_1, pop_pair_2, win_size, statistics) {
  
  # Preparing dataset
  diff_df <- dataset %>%
    drop_na() %>%
    dplyr::select(c(scaffold, start, pop_pair_1, pop_pair_2)) %>% 
    mutate(diff = get(pop_pair_1)-get(pop_pair_2)) %>% # Calculate difference 
    mutate(q_99 = quantile(diff, probs = 0.99, na.rm = T)) %>% # Calculate quantile 99%
    mutate(q_01 = quantile(diff, probs = 0.01, na.rm = T)) %>% # Calculate quantile 1%
    mutate(outlier_q99  = case_when(diff >= q_99 ~ "above",
                                    diff < q_99 & diff > q_01 ~ "notoutlier",
                                    diff <= q_01 ~ "below")) %>% # whether the window is an outlier 
    # Median fst difference per chromosome
    group_by(scaffold) %>%
    dplyr::mutate(median_diff = median(diff, na.rm = T))
  
  # Plotting values across chromosomes
  ggplot(diff_df, aes(start, diff)) + 
    geom_rect(data = dplyr::filter(diff_df, scaffold %% 2 == 1),
              fill = "grey92", color = "grey92", 
              xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf) + #color only odd chromosomes panel
    geom_point(aes(color = factor(outlier_q99, levels = c("notoutlier","below","above")))) +
    scale_color_manual(values = c("#7e7f80", "#40ab99", "#a3526b"), labels = c("notoutlier", "below", "above")) +
    geom_hline(data = diff_df, aes(yintercept = median_diff), linewidth = 0.5, color = "black", linetype= "dotted") +
    facet_grid(~scaffold, scales = 'free_x', space = 'free_x', switch = 'x', labeller = labeller(scaffold = c(1:24))) +
    labs(x        = "chromosome",
         y        = statistics) +
    theme_light() +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          panel.grid = element_blank(),
          axis.title.x = element_blank(),
          axis.title.y = ggtext::element_markdown(color = "grey50"),
          panel.spacing.x = unit(1, "mm"),
          strip.background = element_blank(),
          strip.text.x = element_text(color = "black"),
          panel.border = element_blank(),
          legend.position = "none",
          legend.title = element_blank())
}

# Formula: F1-parent divergence = Fst of CHR-F1  - Fst of SAN-F1 
fig_4a <- fun_diff_pairwise(data_fst_dxy_pi, "Fst_CHR_PNG_leuco_F1", "Fst_leuco_F1_SAN_PNG", "50kb", "*F<sub>ST<sub>* difference")
ggsave(filename = "../plots/fst_diff_chr-f1_san-f1.png", plot = fst, dpi = "print")


## Figure 4B -------------------------------------------------------------------
# Density plot of the different type of windows (background, q01, q99) for the
# two following fdm values:
# fdm1 : p1 = A. sand (aus)  p2 = A. sand (kimbe) p3 = A. chryso (kimbe)
# fdm2 : p1 = A. chryso (fiji) p2 = A. chryso (kimbe) p3 = A. sand (kimbe)
# background windows are labeled 'notoutlier' and highly divergent windows biased 
# toward A. sandaracinos are labeled 'below' in fst$data$outlier_q99

# fdm1 with p1 = sandaracinos australia
fdm_df_san <- left_join(allchr.san.abba, fst$data, by = c("scaffold", "start")) %>%
  drop_na() %>%
  mutate(fdm_test = "san_aus-san_png-chr_png") %>%
  select(c(scaffold, start, fdM, outlier_q99, fdm_test)) %>%
  mutate(window_type = case_when(outlier_q99 == 'below' ~ 'divergent_san',
                                 outlier_q99 == 'notoutlier' ~ 'background',
                                 outlier_q99 == 'above' ~ 'divergent_chp'))

# fdm2 with p1 = chrysopterus fiji
fdm_df_chr <- left_join(allchr.chr.abba, fst$data, by = c("scaffold", "start")) %>%
  drop_na() %>%
  mutate(fdm_test = "chr_fiji-chr_png-san_png") %>%
  select(c(scaffold, start, fdM, outlier_q99, fdm_test)) %>%
  mutate(window_type = case_when(outlier_q99 == 'below' ~ 'divergent_san',
                                 outlier_q99 == 'notoutlier' ~ 'background',
                                 outlier_q99 == 'above' ~ 'divergent_chp'))
# combine the two datasets
fdm_df <- as_tibble(bind_rows(fdm_df_san, fdm_df_chr)) %>%
  mutate(fdm_test = factor(fdm_test, levels = unique(fdm_test))) %>%
  mutate(window_type = factor(window_type, levels = unique(window_type)))


# split violin plots
fig_4b <- ggplot(fdm_df, aes(x = window_type, y = fdM, colour = fdm_test, fill = window_type)) +
  introdataviz::geom_split_violin(alpha = 0.4, trim = FALSE) +
  geom_boxplot(width = 0.2, alpha = 0.6, fatten = NULL, show.legend = FALSE, outlier.alpha = 0) +
  stat_summary(fun = "median", geom = "pointrange", show.legend = F, 
               position = position_dodge(0.2)) +
  scale_y_continuous(name = "fdM", 
                     limits = c(-0.25, 0.25)) +
  #scale_fill_manual(values = c("#40ab99", "#a3526b")) +
  scale_colour_manual(values = c("grey40", "grey20")) +
  scale_fill_manual(values = c("#7e7f80", "#40ab99", "#a3526b")) +
  labs(y = "*F<sub>dM</sub>*") +
  scale_x_discrete(labels = c("Background\nwindows",
                              "Highly divergent\nwindows (A.sandaracinos)",
                              "Highly divergent\nwindows (A.chrysopterus)")) +
  theme_light() +
  theme(axis.title.x = element_blank(),
        axis.title.y = ggtext::element_markdown(colour = "grey50"),
        axis.text.x = element_text(colour = "grey50"),
        legend.position = "none",
        legend.title = element_blank())

## Figure 4 compiled -----------------------------------------------------------

fig_4a + fig_4b + plot_layout(widths = c(2,1)) + plot_annotation(tag_levels = 'A')
ggsave(filename = "../plots/fig4_fdm.png", width = 40, height = 20, units = "cm")
ggsave(filename = "../plots/fig4_fdm.pdf", width = 40, height = 20, units = "cm")


## Additional figures not used in the publication in the end -------------------

## Figure SUPP ###################################################################
# Plot the distribution of fdM (only based on p1 = san aus, p2 = san png and p3 = chr png) across all background windows and highly divergent windows biased toward A. sandaracinos or A. chrysopterus
# Background windows are labeled 'notoutlier' and highly divergent windows biased toward A. sandaracinos are labeled 'below' in fst$data$outlier_q99

fdm_df <- left_join(allchr.san.abba, fst$data, by = c("scaffold", "start")) %>%
  drop_na() %>%
  select(c(scaffold, start, fdM, outlier_q99)) %>%
  mutate(window_type = case_when(outlier_q99 == 'below' ~ 'divergent_san',
                                outlier_q99 == 'notoutlier' ~ 'background',
                                outlier_q99 == 'above' ~ 'divergent_chp'))

order_x <- c("background","divergent_san","divergent_chp")

fdm_san <- ggplot(fdm_df, aes(x = factor(window_type, levels = order_x), y = fdM, colour = factor(window_type, levels = order_x))) +
  geom_boxplot(outlier.shape = NA, width = 0.6) +
  scale_color_manual(values = c("#7e7f80", "#40ab99", "#a3526b"), labels = c("background", "divergent_san", "divergent_chp")) +
  geom_jitter(alpha = 0.4, width = 0.15, size = 0.5) +
  labs(title = "Distribution of fdM",
       y = "*F<sub>dM</sub>*") +
  scale_x_discrete(labels = c("Background\nwindows",
                              "Highly divergent\nwindows (A.sandaracinos)",
                              "Highly divergent\nwindows (A.chrysopterus)")) +
  theme_light() +
  theme(axis.title.x = element_blank(),
        axis.title.y = ggtext::element_markdown(colour = "grey50"),
        axis.text.x = element_text(colour = "grey50"),
        legend.position = "none",
        legend.title = element_blank())

ggsave(filename = "../plots/distribution_fdm_san.png", plot = fdm, dpi = "print")

## Figure SUPP #################################################################
# Plot the distribution of fdM (calculated in two different ways) across all background windows and highly divergent windows biased toward A. sandaracinos or A. chrysopterus
# Background windows are labeled 'notoutlier' and highly divergent windows biased toward A. sandaracinos are labeled 'below' in fst$data$outlier_q99

# fdm with p1 = sandaracinos australia
fdm_df_san <- left_join(allchr.san.abba, fst$data, by = c("scaffold", "start")) %>%
  drop_na() %>%
  mutate(fdm_test = "san_aus-san_png-chr_png") %>%
  select(c(scaffold, start, fdM, outlier_q99, fdm_test)) %>%
  mutate(window_type = case_when(outlier_q99 == 'below' ~ 'divergent_san',
                                 outlier_q99 == 'notoutlier' ~ 'background',
                                 outlier_q99 == 'above' ~ 'divergent_chp'))

# fdm with p1 = chrysopterus fiji
fdm_df_chr <- left_join(allchr.chr.abba, fst$data, by = c("scaffold", "start")) %>%
  drop_na() %>%
  mutate(fdm_test = "chr_fiji-chr_png-san_png") %>%
  select(c(scaffold, start, fdM, outlier_q99, fdm_test)) %>%
  mutate(window_type = case_when(outlier_q99 == 'below' ~ 'divergent_san',
                                 outlier_q99 == 'notoutlier' ~ 'background',
                                 outlier_q99 == 'above' ~ 'divergent_chp'))
# combine the two datasets
fdm_df <- bind_rows(fdm_df_san, fdm_df_chr)

# define order for plotting
order_x <- c("background","divergent_san","divergent_chp")

# plot data
fdm_plot <- ggplot(fdm_df, aes(x = factor(window_type, level = order_x), y = fdM, colour = factor(window_type, level = order_x))) +
  # boxplots for the two fdm_test conditions within each window_type
  geom_boxplot(outlier.shape = NA, width = 0.6, position = position_dodge(width = 0.8)) +
  # jittered points
  geom_jitter(alpha = 0.4, size = 0.5, position = position_dodge(width = 0.8)) +
  # set custom colors for each window type
  scale_color_manual(values = c("#7e7f80", "#40ab99", "#a3526b"), 
                     labels = c("background", "divergent_san", "divergent_chp")) +
  scale_x_discrete(labels = c("Background\nwindows",
                              "Highly divergent\nwindows (A.sandaracinos)",
                              "Highly divergent\nwindows (A.chrysopterus)")) +
  # custom labels and titles
  labs(title = "Distribution of fdM",
       y = "*F<sub>dM</sub>*",
       x = "Window Type") +
  # facet by fdm_test to split the panels
  facet_wrap(~ fdm_test, 
             scales = "free_x", 
             labeller = labeller(fdm_test = c(
               "chr_fiji-chr_png-san_png" = "p1 = chr. fiji, p2 = chr. png, p3 = san. png",
               "san_aus-san_png-chr_png" = "p1 = san. aus, p2 = san. png, p3 = chr png"
             ))) +
  theme_light() +
  theme(axis.title.x = element_blank(),
        axis.title.y = ggtext::element_markdown(colour = "grey50"),
        axis.text.x = element_text(colour = "grey50"),
        legend.position = "none",
        legend.title = element_blank())


ggsave(filename = "../plots/distribution_fdm_san_chr.png", plot = fdm_plot, width = 30, height = 15, units = "cm")


################ Finish ################

